### ISSUE TITLE
Getting Weird Evaluation Issues when following the tutorial. "cannot evaluate a numeric op with unequal lengths"

### ISSUE THREAD

**Issue by Emilio105** [csunlab/GISF2E#2]
Hi

Regardless of the dataset I use, I keep getting this error

Traceback (most recent call last):
  File "C:/Users/UserTwo/PycharmProjects/Mathies/Shape2PlanarGraph.py", line 287, in <module>
    points = sorted(testando.groupby('continuidade').groups[0] + testando.groupby('continuidade').groups[2])
  File "C:\Anaconda3\envs\MathPlayGround\lib\site-packages\pandas\indexes\base.py", line 3495, in _evaluate_numeric_binop
    other = self._validate_for_numeric_binop(other, op, opstr)
  File "C:\Anaconda3\envs\MathPlayGround\lib\site-packages\pandas\indexes\base.py", line 3468, in _validate_for_numeric_binop
    raise ValueError("cannot evaluate a numeric op with "
ValueError: cannot evaluate a numeric op with unequal lengths

I tried changing the groupby method to apply and index with no avail.

Anyhelp here would be amazing.
Thanks

**Comment by csunlab** [comment]
Hi,
Can you clarify whether you are using the Python or QGIS code? Are you using the data set provided with the tutorial as well? Moreover, do you have the latest version of pandas?
Best,
CSUN

**Comment by Emilio105** [comment]
Using the python code, on python 2.7. Am using the data set and following the instructions provided in the tutorial, and am using Pandas V 0.19.2
Tried changing and re downloading the data set contained here: http://csun.uic.edu/codes/GISF2E/Python/GISF2E_python_tutorial.zip

**Comment by Emilio105** [comment]
Rolling Back Pandas to 0.18 seemed to do the trick. But now I'm getting this error:
ERROR 1: Failed to create file .shp file.
ERROR 4: Failed to open Shapefile `C:\Users\UserTwo\PycharmProjects\Mathies/output\Nodes_Chicago_cut.shp'.

Traceback (most recent call last):
  File "C:/Users/EmilChetty/PycharmProjects/Mathies/Shape2PlanarGraph.py", line 301, in <module>
    layer_defn = layer.GetLayerDefn()  # gets parameters of the current shapefile
AttributeError: 'NoneType' object has no attribute 'GetLayerDefn'

**Comment by csunlab** [comment]
We are doing some tests and trying to update the code for Pandas 0.19. We will get back to you as soon as we have an answer.

**Comment by csunlab** [comment]
We have updated the code to work with pandas 0.19.2. Can you try it?

Otherwise, the problem you may have is with your use of slashes since you use a forward slash " / " after "Mathies" in your file path whereas it really should be a backward slash " \ ".
